version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: wednesday
      timezone: Asia/Shanghai
    open-pull-requests-limit: 10
    versioning-strategy: lockfile-only
    ignore:
      - dependency-name: y18n
        versions:
          - 4.0.1
    rebase-strategy: disabled
