name: Unit Tests

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout rgbpp-sdk
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - uses: pnpm/action-setup@v3
        name: Install -g pnpm
        with:
          version: 8
          run_install: false

      - name: Install Deps
        run: pnpm install

      - name: Compile
        run: pnpm lint

      - name: Compile
        run: pnpm build

      - name: Test
        run: pnpm test
